### ISSUE TITLE
Błąd na stronie: _posts/2018-07-26-klauzula-where-w-zapytaniach-sql.md

### ISSUE THREAD

**Issue by 94wojtek** [SamouczekProgramisty/samouczekprogramisty.github.io#22]
Hej,
W części poświęconej LIKE znajduje się zdanie "Zapytanie zwraca wszystkie wiersze, dla których wewnątrz kolumny track występuje znak %:".
O ile dobrze rozumiem temat jak do tej pory to chyba chodzi o tabelę track, a nie kolumnę. 
Wybacz kłopot jeśli źle zrozumiałem. 
Pozdrawiam ;)

**Comment by kbl** [comment]
Dokładnie! Piękne dzięki za zwrócenie uwagi – poprawione! Poprawka będzie widoczna po najbliższej aktualizacji bloga.
