### ISSUE TITLE
Niezwiązane z niczym słowo w treści prezentacji "Początki pracy z wierszem poleceń"

### ISSUE THREAD

**Issue by niemarcin** [SamouczekProgramisty/samouczekprogramisty.github.io#25]
**To jest...** 

- [x] zgłosznie błędu w artykule
- [ ] prośba o nowy artykuł

**Problem:**
Na końcu akapitu "Podstawy pracy z systemem plików" (podlinkowany poniżej), tuż przed akapitem "Ścieżka",  jest wrzucone słowo "Zanim", ale z niczym się ono nie wiąże. 
Chodzi o zdanie:
> Właśnie dzięki takiej praktyce nauczysz się najwięcej. Zanim

**Proponowane rozwiązanie:**
Albo tam miała być kontynuacja myśli, albo słowo jest do usunięcia. ;) 

**Strona do poprawienia:**
https://github.com/SamouczekProgramisty/samouczekprogramisty.github.io/blob/source/_posts/2019-03-12-poczatki-pracy-z-konsola.md#podstawy-pracy-z-systemem-plik%C3%B3w

**Comment by niemarcin** [comment]
@kbl PS. W formularzu zgłoszenia issue, jest literówka ;) 

jest "zgłosznie" zamiast "zgłoszenie"

**Comment by kbl** [comment]
Dzięki za zwrócenie uwagi, rzeczywiście „Zanim” jest do usunięcia :) Oba błędy poprawione! Jeśli coś jeszcze rzuci Ci się w oczy proszę daj znać!

* ac3ab07aab1089490c5fe5d48bc5c4c0348b7a8b
* 0c1c7d90950f2b2bac33c197decfef9c5c2e797a
