### ISSUE TITLE
Literówka: _posts/2015-10-22-metody-w-jezyku-java.md

### ISSUE THREAD

**Issue by Sylwia-code** [SamouczekProgramisty/samouczekprogramisty.github.io#26]
<p>Zadnim przejdę do omówienia metod musisz dowiedzieć się czym są typy danych.</p>

#main > article > div.page__inner-wrap > section > p:nth-child(9)

**Comment by kbl** [comment]
Dzięki za wyłapanie literówki! Błąd już poprawiłem – 1be8d834235984e15d1caf489b17c4afdcc34a7b. Poprawka będzie widoczna po następnej aktualizacji treści bloga.
