### ISSUE TITLE
Błąd na stronie: _posts/2018-02-08-protokol-http.md

### ISSUE THREAD

**Issue by GosiaProc** [SamouczekProgramisty/samouczekprogramisty.github.io#29]
Odpowiedzi na żądania typu POST nie są przechowywane w cache’u

zamiast

Odpowiedzi na żądania typu POST nie jest przechowywana w cache’u

**Comment by kbl** [comment]
Hej! Dzięki za zgłoszenie błędu :) Poprawiłem go tutaj d5ab4460d0a4a15939bb752d1df360c8b167d3a5. Jak coś jeszcze rzuci Ci się w o czy proszę daj znać.
